openapi: 3.1.0
info:
  version: 1.0.0
  title: WaterIn server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: App for monitoring the amount of water consumed
tags:
  - name: Users
    description: Operations about users.
  - name: Water
    description: Operations about water.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://waterin-server.onrender.com
  # - url: server path not config yet
paths:
  /users/register:
    post:
      $ref: ../swagger/paths/auth/{register}/post.yaml
  /users/login:
    post:
      $ref: ../swagger/paths/auth/{login}/post.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/auth/{logout}/post.yaml
  /users/{id}:
    get:
      $ref: ../swagger/paths/users/get.yaml
    patch:
      $ref: ../swagger/paths/users/patch.yaml
  /users/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh-token.yaml'
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water:
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/day:
    get: 
      $ref: ../swagger/paths/water/day/get.yaml
  /water/month:
    get: 
      $ref: ../swagger/paths/water/month/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
